/*****************************************************************************************
Copyright 2018 Dereth Forever

Permission is hereby granted, free of charge, to any person obtaining a copy of this
software and associated documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons
to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or
substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE
FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*****************************************************************************************/
using System.ComponentModel.DataAnnotations;

namespace DerethForever.Web.Models.Enums
{
    public enum IntPropertyId
    {
        [Display(Name                            = "000 - Undef")]
        Undef                                    = 0,
        [Display(Name                            = "001 - Item Type")]
        ItemType                                 = 1,
        [Display(Name                            = "002 - Creature Type")]
        CreatureType                             = 2,
        [Display(Name                            = "003 - Palette Template")]
        PaletteTemplate                          = 3,
        [Display(Name                            = "004 - Clothing Priority")]
        ClothingPriority                         = 4,
        [Display(Name                            = "005 - Encumbrance Val")]
        EncumbranceVal                           = 5,
        [Display(Name                            = "006 - Items Capacity")]
        ItemsCapacity                            = 6,
        [Display(Name                            = "007 - Containers Capacity")]
        ContainersCapacity                       = 7,
        [Display(Name                            = "008 - Mass")]
        Mass                                     = 8,
        [Display(Name                            = "009 - Valid Locations")]
        ValidLocations                           = 9,
        [Display(Name                            = "010 - Current Wielded Location")]
        CurrentWieldedLocation                   = 10,
        [Display(Name                            = "011 - Max Stack Size")]
        MaxStackSize                             = 11,
        [Display(Name                            = "012 - Stack Size")]
        StackSize                                = 12,
        [Display(Name                            = "013 - Stack Unit Encumbrance")]
        StackUnitEncumbrance                     = 13,
        [Display(Name                            = "014 - Stack Unit Mass")]
        StackUnitMass                            = 14,
        [Display(Name                            = "015 - Stack Unit Value")]
        StackUnitValue                           = 15,
        [Display(Name                            = "016 - Item Useable")]
        ItemUseable                              = 16,
        [Display(Name                            = "017 - Rare Id")]
        RareId                                   = 17,
        [Display(Name                            = "018 - Ui Effects")]
        UiEffects                                = 18,
        [Display(Name                            = "019 - Value")]
        Value                                    = 19,
        [Display(Name                            = "020 - Coin Value")]
        CoinValue                                = 20,
        [Display(Name                            = "021 - Total Experience")]
        TotalExperience                          = 21,
        [Display(Name                            = "022 - Available Character")]
        AvailableCharacter                       = 22,
        [Display(Name                            = "023 - Total Skill Credits")]
        TotalSkillCredits                        = 23,
        [Display(Name                            = "024 - Available Skill Credits")]
        AvailableSkillCredits                    = 24,
        [Display(Name                            = "025 - Level")]
        Level                                    = 25,
        [Display(Name                            = "026 - Account Requirements")]
        AccountRequirements                      = 26,
        [Display(Name                            = "027 - Armor Type")]
        ArmorType                                = 27,
        [Display(Name                            = "028 - Armor Level")]
        ArmorLevel                               = 28,
        [Display(Name                            = "029 - Allegiance Cp Pool")]
        AllegianceCpPool                         = 29,
        [Display(Name                            = "030 - Allegiance Rank")]
        AllegianceRank                           = 30,
        [Display(Name                            = "031 - Channels Allowed")]
        ChannelsAllowed                          = 31,
        [Display(Name                            = "032 - Channels Active")]
        ChannelsActive                           = 32,
        [Display(Name                            = "033 - Bonded")]
        Bonded                                   = 33,
        [Display(Name                            = "034 - Monarchs Rank")]
        MonarchsRank                             = 34,
        [Display(Name                            = "035 - Allegiance Followers")]
        AllegianceFollowers                      = 35,
        [Display(Name                            = "036 - Resist Magic")]
        ResistMagic                              = 36,
        [Display(Name                            = "037 - Resist Item Appraisal")]
        ResistItemAppraisal                      = 37,
        [Display(Name                            = "038 - Resist Lockpick")]
        ResistLockpick                           = 38,
        [Display(Name                            = "039 - Deprecated Resist Repair")]
        DeprecatedResistRepair                   = 39,
        [Display(Name                            = "040 - Combat Mode")]
        CombatMode                               = 40,
        [Display(Name                            = "041 - Current Attack Height")]
        CurrentAttackHeight                      = 41,
        [Display(Name                            = "042 - Combat Collisions")]
        CombatCollisions                         = 42,
        [Display(Name                            = "043 - Number Deaths")]
        NumDeaths                                = 43,
        [Display(Name                            = "044 - Damage")]
        Damage                                   = 44,
        [Display(Name                            = "045 - Damage Type")]
        DamageType                               = 45,
        [Display(Name                            = "046 - Default Combat Style")]
        DefaultCombatStyle                       = 46,
        [Display(Name                            = "047 - Attack Type")]
        AttackType                               = 47,
        [Display(Name                            = "048 - Weapon Skill")]
        WeaponSkill                              = 48,
        [Display(Name                            = "049 - Weapon Time")]
        WeaponTime                               = 49,
        [Display(Name                            = "050 - Ammo Type")]
        AmmoType                                 = 50,
        [Display(Name                            = "051 - Combat Use")]
        CombatUse                                = 51,
        [Display(Name                            = "052 - Parent Location")]
        ParentLocation                           = 52,
        [Display(Name                            = "053 - Placement Position")]
        PlacementPosition                        = 53,
        [Display(Name                            = "054 - Weapon Encumbrance")]
        WeaponEncumbrance                        = 54,
        [Display(Name                            = "055 - Weapon Mass")]
        WeaponMass                               = 55,
        [Display(Name                            = "056 - Shield Value")]
        ShieldValue                              = 56,
        [Display(Name                            = "057 - Shield Encumbrance")]
        ShieldEncumbrance                        = 57,
        [Display(Name                            = "058 - Missile Inventory Location")]
        MissileInventoryLocation                 = 58,
        [Display(Name                            = "059 - Full Damage Type")]
        FullDamageType                           = 59,
        [Display(Name                            = "060 - Weapon Range")]
        WeaponRange                              = 60,
        [Display(Name                            = "061 - Attackers Skill")]
        AttackersSkill                           = 61,
        [Display(Name                            = "062 - Defenders Skill")]
        DefendersSkill                           = 62,
        [Display(Name                            = "063 - Attackers Skill Value")]
        AttackersSkillValue                      = 63,
        [Display(Name                            = "064 - Attackers Class")]
        AttackersClass                           = 64,
        [Display(Name                            = "065 - Placement")]
        Placement                                = 65,
        [Display(Name                            = "066 - Checkpoint Status")]
        CheckpointStatus                         = 66,
        [Display(Name                            = "067 - Tolerance")]
        Tolerance                                = 67,
        [Display(Name                            = "068 - Targeting Tactic")]
        TargetingTactic                          = 68,
        [Display(Name                            = "069 - Combat Tactic")]
        CombatTactic                             = 69,
        [Display(Name                            = "070 - Homesick Targeting Tactic")]
        HomesickTargetingTactic                  = 70,
        [Display(Name                            = "071 - Number Follow Failures")]
        NumFollowFailures                        = 71,
        [Display(Name                            = "072 - Friend Type")]
        FriendType                               = 72,
        [Display(Name                            = "073 - Foe Type")]
        FoeType                                  = 73,
        [Display(Name                            = "074 - Merchandise Item Types")]
        MerchandiseItemTypes                     = 74,
        [Display(Name                            = "075 - Merchandise Min Value")]
        MerchandiseMinValue                      = 75,
        [Display(Name                            = "076 - Merchandise Max Value")]
        MerchandiseMaxValue                      = 76,
        [Display(Name                            = "077 - Number Items Sold")]
        NumItemsSold                             = 77,
        [Display(Name                            = "078 - Number Items Bought")]
        NumItemsBought                           = 78,
        [Display(Name                            = "079 - Money Income")]
        MoneyIncome                              = 79,
        [Display(Name                            = "080 - Money Outflow")]
        MoneyOutflow                             = 80,
        [Display(Name                            = "081 - Max Generated Objects")]
        MaxGeneratedObjects                      = 81,
        [Display(Name                            = "082 - Init Generated Objects")]
        InitGeneratedObjects                     = 82,
        [Display(Name                            = "083 - Activation Response")]
        ActivationResponse                       = 83,
        [Display(Name                            = "084 - Original Value")]
        OriginalValue                            = 84,
        [Display(Name                            = "085 - Number Move Failures")]
        NumMoveFailures                          = 85,
        [Display(Name                            = "086 - Min Level")]
        MinLevel                                 = 86,
        [Display(Name                            = "087 - Max Level")]
        MaxLevel                                 = 87,
        [Display(Name                            = "088 - Lockpick Mod")]
        LockpickMod                              = 88,
        [Display(Name                            = "089 - Booster Enum")]
        BoosterEnum                              = 89,
        [Display(Name                            = "090 - Boost Value")]
        BoostValue                               = 90,
        [Display(Name                            = "091 - Max Structure")]
        MaxStructure                             = 91,
        [Display(Name                            = "092 - Structure")]
        Structure                                = 92,
        [Display(Name                            = "093 - Physics State")]
        PhysicsState                             = 93,
        [Display(Name                            = "094 - Target Type")]
        TargetType                               = 94,
        [Display(Name                            = "095 - Radar Blip Color")]
        RadarBlipColor                           = 95,
        [Display(Name                            = "096 - Encumbrance Capacity")]
        EncumbranceCapacity                      = 96,
        [Display(Name                            = "097 - Login Timestamp")]
        LoginTimestamp                           = 97,
        [Display(Name                            = "098 - Creation Timestamp")]
        CreationTimestamp                        = 98,
        [Display(Name                            = "099 - Pk Level Modifier")]
        PkLevelModifier                          = 99,
        [Display(Name                            = "100 - Generator Type")]
        GeneratorType                            = 100,
        [Display(Name                            = "101 - Ai Allowed Combat Style")]
        AiAllowedCombatStyle                     = 101,
        [Display(Name                            = "102 - Logoff Timestamp")]
        LogoffTimestamp                          = 102,
        [Display(Name                            = "103 - Generator Destruction Type")]
        GeneratorDestructionType                 = 103,
        [Display(Name                            = "104 - Activation Create Class")]
        ActivationCreateClass                    = 104,
        [Display(Name                            = "105 - Item Workmanship")]
        ItemWorkmanship                          = 105,
        [Display(Name                            = "106 - Item Spellcraft")]
        ItemSpellcraft                           = 106,
        [Display(Name                            = "107 - Item Cur Mana")]
        ItemCurMana                              = 107,
        [Display(Name                            = "108 - Item Max Mana")]
        ItemMaxMana                              = 108,
        [Display(Name                            = "109 - Item Difficulty")]
        ItemDifficulty                           = 109,
        [Display(Name                            = "110 - Item Allegiance Rank Limit")]
        ItemAllegianceRankLimit                  = 110,
        [Display(Name                            = "111 - Portal Bitmask")]
        PortalBitmask                            = 111,
        [Display(Name                            = "112 - Advocate Level")]
        AdvocateLevel                            = 112,
        [Display(Name                            = "113 - Gender")]
        Gender                                   = 113,
        [Display(Name                            = "114 - Attuned")]
        Attuned                                  = 114,
        [Display(Name                            = "115 - Item Skill Level Limit")]
        ItemSkillLevelLimit                      = 115,
        [Display(Name                            = "116 - Gate Logic")]
        GateLogic                                = 116,
        [Display(Name                            = "117 - Item Mana Cost")]
        ItemManaCost                             = 117,
        [Display(Name                            = "118 - Logoff")]
        Logoff                                   = 118,
        [Display(Name                            = "119 - Active")]
        Active                                   = 119,
        [Display(Name                            = "120 - Attack Height")]
        AttackHeight                             = 120,
        [Display(Name                            = "121 - Num Attack Failures")]
        NumAttackFailures                        = 121,
        [Display(Name                            = "122 - Ai Cp Threshold")]
        AiCpThreshold                            = 122,
        [Display(Name                            = "123 - Ai Advancement Strategy")]
        AiAdvancementStrategy                    = 123,
        [Display(Name                            = "124 - Version")]
        Version                                  = 124,
        [Display(Name                            = "125 - Age")]
        Age                                      = 125,
        [Display(Name                            = "126 - Vendor Happy Mean")]
        VendorHappyMean                          = 126,
        [Display(Name                            = "127 - Vendor Happy Variance")]
        VendorHappyVariance                      = 127,
        [Display(Name                            = "128 - Cloak Status")]
        CloakStatus                              = 128,
        [Display(Name                            = "129 - Vitae Cp Pool")]
        VitaeCpPool                              = 129,
        [Display(Name                            = "130 - Number Services Sold")]
        NumServicesSold                          = 130,
        [Display(Name                            = "131 - Material Type")]
        MaterialType                             = 131,
        [Display(Name                            = "132 - Number Allegiance Breaks")]
        NumAllegianceBreaks                      = 132,
        [Display(Name                            = "133 - Showable On Radar")]
        ShowableOnRadar                          = 133,
        [Display(Name                            = "134 - Player Killer Status")]
        PlayerKillerStatus                       = 134,
        [Display(Name                            = "135 - Vendor Happy Max Items")]
        VendorHappyMaxItems                      = 135,
        [Display(Name                            = "136 - Score Page Number")]
        ScorePageNum                             = 136,
        [Display(Name                            = "137 - Score Config Num")]
        ScoreConfigNum                           = 137,
        [Display(Name                            = "138 - Score Num Scores")]
        ScoreNumScores                           = 138,
        [Display(Name                            = "139 - Death Level")]
        DeathLevel                               = 139,
        [Display(Name                            = "140 - Ai Options")]
        AiOptions                                = 140,
        [Display(Name                            = "141 - Open To Everyone")]
        OpenToEveryone                           = 141,
        [Display(Name                            = "142 - Generator Time Type")]
        GeneratorTimeType                        = 142,
        [Display(Name                            = "143 - Generator Start Time")]
        GeneratorStartTime                       = 143,
        [Display(Name                            = "144 - Generator End Time")]
        GeneratorEndTime                         = 144,
        [Display(Name                            = "145 - Generator End Destruction Type")]
        GeneratorEndDestructionType              = 145,
        [Display(Name                            = "146 - Xp Override")]
        XpOverride                               = 146,
        [Display(Name                            = "147 - Number Crash And Turns")]
        NumCrashAndTurns                         = 147,
        [Display(Name                            = "148 - Component Warning Threshold")]
        ComponentWarningThreshold                = 148,
        [Display(Name                            = "149 - House Status")]
        HouseStatus                              = 149,
        [Display(Name                            = "150 - Hook Placement")]
        HookPlacement                            = 150,
        [Display(Name                            = "151 - Hook Type")]
        HookType                                 = 151,
        [Display(Name                            = "152 - Hook Item Type")]
        HookItemType                             = 152,
        [Display(Name                            = "153 - Ai Pp Threshold")]
        AiPpThreshold                            = 153,
        [Display(Name                            = "154 - Generator Version")]
        GeneratorVersion                         = 154,
        [Display(Name                            = "155 - House Type")]
        HouseType                                = 155,
        [Display(Name                            = "156 - Pickup Emote Offset")]
        PickupEmoteOffset                        = 156,
        [Display(Name                            = "157 - Weenie Iteration")]
        WeenieIteration                          = 157,
        [Display(Name                            = "158 - Wield Requirements")]
        WieldRequirements                        = 158,
        [Display(Name                            = "159 - Wield Skilltype")]
        WieldSkilltype                           = 159,
        [Display(Name                            = "160 - Wield Difficulty")]
        WieldDifficulty                          = 160,
        [Display(Name                            = "161 - House Max Hooks Usable")]
        HouseMaxHooksUsable                      = 161,
        [Display(Name                            = "162 - House Current Hooks Usable")]
        HouseCurrentHooksUsable                  = 162,
        [Display(Name                            = "163 - Allegiance Min Level")]
        AllegianceMinLevel                       = 163,
        [Display(Name                            = "164 - Allegiance Max Level")]
        AllegianceMaxLevel                       = 164,
        [Display(Name                            = "165 - House Relink Hook Count")]
        HouseRelinkHookCount                     = 165,
        [Display(Name                            = "166 - Slayer Creature Type")]
        SlayerCreatureType                       = 166,
        [Display(Name                            = "167 - Confirmation In Progress")]
        ConfirmationInProgress                   = 167,
        [Display(Name                            = "168 - Confirmation Type In Progress")]
        ConfirmationTypeInProgress               = 168,
        [Display(Name                            = "169 - Tsys Mutation Data")]
        TsysMutationData                         = 169,
        [Display(Name                            = "170 - Number Items In Material")]
        NumItemsInMaterial                       = 170,
        [Display(Name                            = "171 - Number Times Tinkered")]
        NumTimesTinkered                         = 171,
        [Display(Name                            = "172 - Appraisal Long Desc Decoration")]
        AppraisalLongDescDecoration              = 172,
        [Display(Name                            = "173 - Appraisal Lockpick Success Percent")]
        AppraisalLockpickSuccessPercent          = 173,
        [Display(Name                            = "174 - Appraisal Pages")]
        AppraisalPages                           = 174,
        [Display(Name                            = "175 - Appraisal Max Pages")]
        AppraisalMaxPages                        = 175,
        [Display(Name                            = "176 - Appraisal Item Skill")]
        AppraisalItemSkill                       = 176,
        [Display(Name                            = "177 - Gem Count")]
        GemCount                                 = 177,
        [Display(Name                            = "178 - Gem Type")]
        GemType                                  = 178,
        [Display(Name                            = "179 - Imbued Effect")]
        ImbuedEffect                             = 179,
        [Display(Name                            = "180 - Attackers Raw Skill Value")]
        AttackersRawSkillValue                   = 180,
        [Display(Name                            = "181 - Chess Rank")]
        ChessRank                                = 181,
        [Display(Name                            = "182 - Chess Total Games")]
        ChessTotalGames                          = 182,
        [Display(Name                            = "183 - Chess Games Won")]
        ChessGamesWon                            = 183,
        [Display(Name                            = "184 - Chess Games Lost")]
        ChessGamesLost                           = 184,
        [Display(Name                            = "185 - Type Of Alteration")]
        TypeOfAlteration                         = 185,
        [Display(Name                            = "186 - Skill To Be Altered")]
        SkillToBeAltered                         = 186,
        [Display(Name                            = "187 - Skill Alteration Count")]
        SkillAlterationCount                     = 187,
        [Display(Name                            = "188 - Heritage Group")]
        HeritageGroup                            = 188,
        [Display(Name                            = "189 - Transfer From Attribute")]
        TransferFromAttribute                    = 189,
        [Display(Name                            = "190 - Transfer To Attribute")]
        TransferToAttribute                      = 190,
        [Display(Name                            = "191 - Attribute Transfer Count")]
        AttributeTransferCount                   = 191,
        [Display(Name                            = "192 - Fake Fishing Skill")]
        FakeFishingSkill                         = 192,
        [Display(Name                            = "193 - Number Keys")]
        NumKeys                                  = 193,
        [Display(Name                            = "194 - Death Timestamp")]
        DeathTimestamp                           = 194,
        [Display(Name                            = "195 - Pk Timestamp")]
        PkTimestamp                              = 195,
        [Display(Name                            = "196 - Victim Timestamp")]
        VictimTimestamp                          = 196,
        [Display(Name                            = "197 - Hook Group")]
        HookGroup                                = 197,
        [Display(Name                            = "198 - Allegiance Swear Timestamp")]
        AllegianceSwearTimestamp                 = 198,
        [Display(Name                            = "199 - House Purchase Timestamp")]
        HousePurchaseTimestamp                   = 199,
        [Display(Name                            = "200 - Redirectable Equipped Armor Count")]
        RedirectableEquippedArmorCount           = 200,
        [Display(Name                            = "201 - Melee Defense Imbued Effect Type Cache")]
        MeleedefenseImbuedEffectTypeCache        = 201,
        [Display(Name                            = "202 - Missile Defense Imbued Effect Type Cache")]
        MissileDefenseImbuedEffectTypeCache      = 202,
        [Display(Name                            = "203 - Magic Defense Imbued Effect Type Cache")]
        MagicDefenseImbuedEffectTypeCache        = 203,
        [Display(Name                            = "204 - Elemental Damage Bonus")]
        ElementalDamageBonus                     = 204,
        [Display(Name                            = "205 - Imbue Attempts")]
        ImbueAttempts                            = 205,
        [Display(Name                            = "206 - Imbue Successes")]
        ImbueSuccesses                           = 206,
        [Display(Name                            = "207 - Creature Kills")]
        CreatureKills                            = 207,
        [Display(Name                            = "208 - Player Kills PK")]
        PlayerKillsPk                            = 208,
        [Display(Name                            = "209 - Player Kills PKL")]
        PlayerKillsPkl                           = 209,
        [Display(Name                            = "210 - Rares Tier One")]
        RaresTierOne                             = 210,
        [Display(Name                            = "211 - Rares Tier Two")]
        RaresTierTwo                             = 211,
        [Display(Name                            = "212 - Rares Tier Three")]
        RaresTierThree                           = 212,
        [Display(Name                            = "213 - Rares Tier Four")]
        RaresTierFour                            = 213,
        [Display(Name                            = "214 - Rares Tier Five")]
        RaresTierFive                            = 214,
        [Display(Name                            = "215 - Augmentation Stat")]
        AugmentationStat                         = 215,
        [Display(Name                            = "216 - Augmentation Family Stat")]
        AugmentationFamilyStat                   = 216,
        [Display(Name                            = "217 - Augmentation Innate Family")]
        AugmentationInnateFamily                 = 217,
        [Display(Name                            = "218 - Augmentation Innate Strength")]
        AugmentationInnateStrength               = 218,
        [Display(Name                            = "219 - Augmentation Innate Endurance")]
        AugmentationInnateEndurance              = 219,
        [Display(Name                            = "220 - Augmentation Innate Coordination")]
        AugmentationInnateCoordination           = 220,
        [Display(Name                            = "221 - Augmentation Innate Quickness")]
        AugmentationInnateQuickness              = 221,
        [Display(Name                            = "222 - Augmentation Innate Focus")]
        AugmentationInnateFocus                  = 222,
        [Display(Name                            = "223 - Augmentation Innate Self")]
        AugmentationInnateSelf                   = 223,
        [Display(Name                            = "224 - Augmentation Specialize Salvaging")]
        AugmentationSpecializeSalvaging          = 224,
        [Display(Name                            = "225 - Augmentation Specialize Item Tinkering")]
        AugmentationSpecializeItemTinkering      = 225,
        [Display(Name                            = "226 - Augmentation Specialize Armor Tinkering")]
        AugmentationSpecializeArmorTinkering     = 226,
        [Display(Name                            = "227 - Augmentation Specialize Magic Item Tinkering")]
        AugmentationSpecializeMagicItemTinkering = 227,
        [Display(Name                            = "228 - Augmentation Specialize Weapon Tinkering")]
        AugmentationSpecializeWeaponTinkering    = 228,
        [Display(Name                            = "229 - Augmentation Extra Pack Slot")]
        AugmentationExtraPackSlot                = 229,
        [Display(Name                            = "230 - Augmentation Increased Carrying Capacity")]
        AugmentationIncreasedCarryingCapacity    = 230,
        [Display(Name                            = "231 - Augmentation Less Death Item Loss")]
        AugmentationLessDeathItemLoss            = 231,
        [Display(Name                            = "232 - Augmentation Spells Remain Past Death")]
        AugmentationSpellsRemainPastDeath        = 232,
        [Display(Name                            = "233 - Augmentation Critical Defense")]
        AugmentationCriticalDefense              = 233,
        [Display(Name                            = "234 - Augmentation Bonus Xp")]
        AugmentationBonusXp                      = 234,
        [Display(Name                            = "235 - Augmentation Bonus Salvage")]
        AugmentationBonusSalvage                 = 235,
        [Display(Name                            = "236 - Augmentation Bonus Imbue Chance")]
        AugmentationBonusImbueChance             = 236,
        [Display(Name                            = "237 - Augmentation Faster Regen")]
        AugmentationFasterRegen                  = 237,
        [Display(Name                            = "238 - Augmentation Increased Spell Duration")]
        AugmentationIncreasedSpellDuration       = 238,
        [Display(Name                            = "239 - Augmentation Resistance Family")]
        AugmentationResistanceFamily             = 239,
        [Display(Name                            = "240 - Augmentation Resistance Slash")]
        AugmentationResistanceSlash              = 240,
        [Display(Name                            = "241 - Augmentation Resistance Pierce")]
        AugmentationResistancePierce             = 241,
        [Display(Name                            = "242 - Augmentation Resistance Blunt")]
        AugmentationResistanceBlunt              = 242,
        [Display(Name                            = "243 - Augmentation Resistance Acid")]
        AugmentationResistanceAcid               = 243,
        [Display(Name                            = "244 - Augmentation Resistance Fire")]
        AugmentationResistanceFire               = 244,
        [Display(Name                            = "245 - Augmentation Resistance Frost")]
        AugmentationResistanceFrost              = 245,
        [Display(Name                            = "246 - Augmentation Resistance Lightning")]
        AugmentationResistanceLightning          = 246,
        [Display(Name                            = "247 - Rares Tier One Login")]
        RaresTierOneLogin                        = 247,
        [Display(Name                            = "248 - Rares Tier Two Login")]
        RaresTierTwoLogin                        = 248,
        [Display(Name                            = "249 - Rares Tier Three Login")]
        RaresTierThreeLogin                      = 249,
        [Display(Name                            = "250 - Rares Tier Four Login")]
        RaresTierFourLogin                       = 250,
        [Display(Name                            = "251 - Rares Tier Five Login")]
        RaresTierFiveLogin                       = 251,
        [Display(Name                            = "252 - Rares Login Timestamp")]
        RaresLoginTimestamp                      = 252,
        [Display(Name                            = "253 - Rares Tier Six")]
        RaresTierSix                             = 253,
        [Display(Name                            = "254 - Rares Tier Seven")]
        RaresTierSeven                           = 254,
        [Display(Name                            = "255 - Rares Tier Six Login")]
        RaresTierSixLogin                        = 255,
        [Display(Name                            = "256 - Rares Tier Seven Login")]
        RaresTierSevenLogin                      = 256,
        [Display(Name                            = "257 - Item Attribute Limit")]
        ItemAttributeLimit                       = 257,
        [Display(Name                            = "258 - Item Attribute Level Limit")]
        ItemAttributeLevelLimit                  = 258,
        [Display(Name                            = "259 - Item Attribute 2nd Limit")]
        ItemAttribute2ndLimit                    = 259,
        [Display(Name                            = "260 - Item Attribute 2nd Level Limit")]
        ItemAttribute2ndLevelLimit               = 260,
        [Display(Name                            = "261 - Character Title Id")]
        CharacterTitleId                         = 261,
        [Display(Name                            = "262 - Number Character Titles")]
        NumCharacterTitles                       = 262,
        [Display(Name                            = "263 - Resistance Modifier Type")]
        ResistanceModifierType                   = 263,
        [Display(Name                            = "264 - Free Tinkers Bitfield")]
        FreeTinkersBitfield                      = 264,
        [Display(Name                            = "265 - Equipment Set Id")]
        EquipmentSetId                           = 265,
        [Display(Name                            = "266 - Pet Class")]
        PetClass                                 = 266,
        [Display(Name                            = "267 - Lifespan")]
        Lifespan                                 = 267,
        [Display(Name                            = "268 - Remaining Lifespan")]
        RemainingLifespan                        = 268,
        [Display(Name                            = "269 - Use Create Quantity")]
        UseCreateQuantity                        = 269,
        [Display(Name                            = "270 - Wield Requirements 2")]
        WieldRequirements2                       = 270,
        [Display(Name                            = "271 - Wield Skilltype 2")]
        WieldSkilltype2                          = 271,
        [Display(Name                            = "272 - Wield Difficulty 2")]
        WieldDifficulty2                         = 272,
        [Display(Name                            = "273 - Wield Requirements 3")]
        WieldRequirements3                       = 273,
        [Display(Name                            = "274 - Wield Skilltype 3")]
        WieldSkilltype3                          = 274,
        [Display(Name                            = "275 - Wield Difficulty 3")]
        WieldDifficulty3                         = 275,
        [Display(Name                            = "276 - Wield Requirements 4")]
        WieldRequirements4                       = 276,
        [Display(Name                            = "277 - Wield Skilltype 4")]
        WieldSkilltype4                          = 277,
        [Display(Name                            = "278 - Wield Difficulty 4")]
        WieldDifficulty4                         = 278,
        [Display(Name                            = "279 - Unique")]
        Unique                                   = 279,
        [Display(Name                            = "280 - Shared Cooldown")]
        SharedCooldown                           = 280,
        [Display(Name                            = "281 - Faction 1 Bits")]
        Faction1Bits                             = 281,
        [Display(Name                            = "282 - Faction 2 Bits")]
        Faction2Bits                             = 282,
        [Display(Name                            = "283 - Faction 3 Bits")]
        Faction3Bits                             = 283,
        [Display(Name                            = "284 - Hatred 1 Bits")]
        Hatred1Bits                              = 284,
        [Display(Name                            = "285 - Hatred 2 Bits")]
        Hatred2Bits                              = 285,
        [Display(Name                            = "286 - Hatred 3 Bits")]
        Hatred3Bits                              = 286,
        [Display(Name                            = "287 - Society Rank Celhan")]
        SocietyRankCelhan                        = 287,
        [Display(Name                            = "288 - Society Rank Eldweb")]
        SocietyRankEldweb                        = 288,
        [Display(Name                            = "289 - Society Rank Radblo")]
        SocietyRankRadblo                        = 289,
        [Display(Name                            = "290 - Hear Local Signals")]
        HearLocalSignals                         = 290,
        [Display(Name                            = "291 - Hear Local Signals Radius")]
        HearLocalSignalsRadius                   = 291,
        [Display(Name                            = "292 - Cleaving")]
        Cleaving                                 = 292,
        [Display(Name                            = "293 - Augmentation Specialize Gearcraft")]
        AugmentationSpecializeGearcraft          = 293,
        [Display(Name                            = "294 - Augmentation Infused Creature Magic")]
        AugmentationInfusedCreatureMagic         = 294,
        [Display(Name                            = "295 - Augmentation Infused Item Magic")]
        AugmentationInfusedItemMagic             = 295,
        [Display(Name                            = "296 - Augmentation Infused Life Magic")]
        AugmentationInfusedLifeMagic             = 296,
        [Display(Name                            = "297 - Augmentation Infused War Magic")]
        AugmentationInfusedWarMagic              = 297,
        [Display(Name                            = "298 - Augmentation Critical Expertise")]
        AugmentationCriticalExpertise            = 298,
        [Display(Name                            = "299 - Augmentation Critical Power")]
        AugmentationCriticalPower                = 299,
        [Display(Name                            = "300 - Augmentation Skilled Melee")]
        AugmentationSkilledMelee                 = 300,
        [Display(Name                            = "301 - Augmentation Skilled Missile")]
        AugmentationSkilledMissile               = 301,
        [Display(Name                            = "302 - Augmentation Skilled Magic")]
        AugmentationSkilledMagic                 = 302,
        [Display(Name                            = "303 - Imbued Effect 2")]
        ImbuedEffect2                            = 303,
        [Display(Name                            = "304 - Imbued Effect 3")]
        ImbuedEffect3                            = 304,
        [Display(Name                            = "305 - Imbued Effect 4")]
        ImbuedEffect4                            = 305,
        [Display(Name                            = "306 - Imbued Effect 5")]
        ImbuedEffect5                            = 306,
        [Display(Name                            = "307 - Damage Rating")]
        DamageRating                             = 307,
        [Display(Name                            = "308 - Damage Resist Rating")]
        DamageResistRating                       = 308,
        [Display(Name                            = "309 - Augmentation Damage Bonus")]
        AugmentationDamageBonus                  = 309,
        [Display(Name                            = "310 - Augmentation Damage Reduction")]
        AugmentationDamageReduction              = 310,
        [Display(Name                            = "311 - Imbue Stacking Bits")]
        ImbueStackingBits                        = 311,
        [Display(Name                            = "312 - Heal Over Time")]
        HealOverTime                             = 312,
        [Display(Name                            = "313 - Crit Rating")]
        CritRating                               = 313,
        [Display(Name                            = "314 - Crit Damage Rating")]
        CritDamageRating                         = 314,
        [Display(Name                            = "315 - Crit Resist Rating")]
        CritResistRating                         = 315,
        [Display(Name                            = "316 - Crit Damage Resist Rating")]
        CritDamageResistRating                   = 316,
        [Display(Name                            = "317 - Healing Resist Rating")]
        HealingResistRating                      = 317,
        [Display(Name                            = "318 - Damage Over Time")]
        DamageOverTime                           = 318,
        [Display(Name                            = "319 - Item Max Level")]
        ItemMaxLevel                             = 319,
        [Display(Name                            = "320 - Item Xp Style")]
        ItemXpStyle                              = 320,
        [Display(Name                            = "321 - Equipment Set Extra")]
        EquipmentSetExtra                        = 321,
        [Display(Name                            = "322 - Aetheria Bitfield")]
        AetheriaBitfield                         = 322,
        [Display(Name                            = "323 - Healing Boost Rating")]
        HealingBoostRating                       = 323,
        [Display(Name                            = "324 - Heritage Specific Armor")]
        HeritageSpecificArmor                    = 324,
        [Display(Name                            = "325 - Alternate Racial Skills")]
        AlternateRacialSkills                    = 325,
        [Display(Name                            = "326 - Augmentation Jack Of All Trades")]
        AugmentationJackOfAllTrades              = 326,
        [Display(Name                            = "327 - Augmentation Resistance Nether")]
        AugmentationResistanceNether             = 327,
        [Display(Name                            = "328 - Augmentation Infused Void Magic")]
        AugmentationInfusedVoidMagic             = 328,
        [Display(Name                            = "329 - Weakness Rating")]
        WeaknessRating                           = 329,
        [Display(Name                            = "330 - Nether Over Time")]
        NetherOverTime                           = 330,
        [Display(Name                            = "331 - Nether Resist Rating")]
        NetherResistRating                       = 331,
        [Display(Name                            = "332 - Luminance Award")]
        LuminanceAward                           = 332,
        [Display(Name                            = "333 - Lum Aug Damage Rating")]
        LumAugDamageRating                       = 333,
        [Display(Name                            = "334 - Lum Aug Damage Reduction Rating")]
        LumAugDamageReductionRating              = 334,
        [Display(Name                            = "335 - Lum Aug Crit Damage Rating")]
        LumAugCritDamageRating                   = 335,
        [Display(Name                            = "336 - Lum Aug Crit Reduction Rating")]
        LumAugCritReductionRating                = 336,
        [Display(Name                            = "337 - Lum Aug Surge Effect Rating")]
        LumAugSurgeEffectRating                  = 337,
        [Display(Name                            = "338 - Lum Aug Surge Chance Rating")]
        LumAugSurgeChanceRating                  = 338,
        [Display(Name                            = "339 - Lum Aug Item Mana Usage")]
        LumAugItemManaUsage                      = 339,
        [Display(Name                            = "340 - Lum Aug Item Mana Gain")]
        LumAugItemManaGain                       = 340,
        [Display(Name                            = "341 - Lum Aug Vitality")]
        LumAugVitality                           = 341,
        [Display(Name                            = "342 - Lum Aug Healing Rating")]
        LumAugHealingRating                      = 342,
        [Display(Name                            = "343 - Lum Aug Skilled Craft")]
        LumAugSkilledCraft                       = 343,
        [Display(Name                            = "344 - Lum Aug Skilled Spec")]
        LumAugSkilledSpec                        = 344,
        [Display(Name                            = "345 - Lum Aug No Destroy Craft")]
        LumAugNoDestroyCraft                     = 345,
        [Display(Name                            = "346 - Restrict Interaction")]
        RestrictInteraction                      = 346,
        [Display(Name                            = "347 - Olthoi Loot Timestamp")]
        OlthoiLootTimestamp                      = 347,
        [Display(Name                            = "348 - Olthoi Loot Step")]
        OlthoiLootStep                           = 348,
        [Display(Name                            = "349 - Use Creates Contract Id")]
        UseCreatesContractId                     = 349,
        [Display(Name                            = "350 - Dot Resist Rating")]
        DotResistRating                          = 350,
        [Display(Name                            = "351 - Life Resist Rating")]
        LifeResistRating                         = 351,
        [Display(Name                            = "352 - Cloak Weave Proc")]
        CloakWeaveProc                           = 352,
        [Display(Name                            = "353 - Weapon Type")]
        WeaponType                               = 353,
        [Display(Name                            = "354 - Melee Mastery")]
        MeleeMastery                             = 354,
        [Display(Name                            = "355 - Ranged Mastery")]
        RangedMastery                            = 355,
        [Display(Name                            = "356 - Sneak Attack Rating")]
        SneakAttackRating                        = 356,
        [Display(Name                            = "357 - Recklessness Rating")]
        RecklessnessRating                       = 357,
        [Display(Name                            = "358 - Deception Rating")]
        DeceptionRating                          = 358,
        [Display(Name                            = "359 - Combat Pet Range")]
        CombatPetRange                           = 359,
        [Display(Name                            = "360 - Weapon Aura Damage")]
        WeaponAuraDamage                         = 360,
        [Display(Name                            = "361 - Weapon Aura Speed")]
        WeaponAuraSpeed                          = 361,
        [Display(Name                            = "362 - Summoning Mastery")]
        SummoningMastery                         = 362,
        [Display(Name                            = "363 - Heartbeat Lifespan")]
        HeartbeatLifespan                        = 363,
        [Display(Name                            = "364 - Use Level Requirement")]
        UseLevelRequirement                      = 364,
        [Display(Name                            = "365 - Lum Aug All Skills")]
        LumAugAllSkills                          = 365,
        [Display(Name                            = "366 - Use Requires Skill")]
        UseRequiresSkill                         = 366,
        [Display(Name                            = "367 - Use Requires Skill Level")]
        UseRequiresSkillLevel                    = 367,
        [Display(Name                            = "368 - Use Requires Skill Spec")]
        UseRequiresSkillSpec                     = 368,
        [Display(Name                            = "369 - Use Requires Level")]
        UseRequiresLevel                         = 369,
        [Display(Name                            = "370 - Gear Damage")]
        GearDamage                               = 370,
        [Display(Name                            = "371 - Gear Damage Resist")]
        GearDamageResist                         = 371,
        [Display(Name                            = "372 - Gear Crit")]
        GearCrit                                 = 372,
        [Display(Name                            = "373 - Gear Crit Resist")]
        GearCritResist                           = 373,
        [Display(Name                            = "374 - Gear Crit Damage")]
        GearCritDamage                           = 374,
        [Display(Name                            = "375 - Gear Crit Damage Resist")]
        GearCritDamageResist                     = 375,
        [Display(Name                            = "376 - Gear Healing Boost")]
        GearHealingBoost                         = 376,
        [Display(Name                            = "377 - Gear Nether Resist")]
        GearNetherResist                         = 377,
        [Display(Name                            = "378 - Gear Life Resist")]
        GearLifeResist                           = 378,
        [Display(Name                            = "379 - Gear Max Health")]
        GearMaxHealth                            = 379,
        [Display(Name                            = "380 - Unknown 3 8 0")]
        Unknown380                               = 380,
        [Display(Name                            = "381 - P K Damage Rating")]
        PKDamageRating                           = 381,
        [Display(Name                            = "382 - P K Damage Resist Rating")]
        PKDamageResistRating                     = 382,
        [Display(Name                            = "383 - Gear P K Damage Rating")]
        GearPKDamageRating                       = 383,
        [Display(Name                            = "384 - Gear P K Damage Resist Rating")]
        GearPKDamageResistRating                 = 384,
        [Display(Name                            = "385 - Unknown 3 8 5")]
        Unknown385                               = 385,
        [Display(Name                            = "386 - Overpower")]
        Overpower                                = 386,
        [Display(Name                            = "387 - Overpower Resist")]
        OverpowerResist                          = 387,
        [Display(Name                            = "388 - Gear Overpower")]
        GearOverpower                            = 388,
        [Display(Name                            = "389 - Gear Overpower Resist")]
        GearOverpowerResist                      = 389,
        [Display(Name                            = "390 - Enlightenment")]
        Enlightenment                            = 390,
        [Display(Name                            = "9001 - Total Logins")]
        TotalLogins                              = 9001,
        [Display(Name                            = "9002 - Deletion Timestamp")]
        DeletionTimestamp                        = 9002,
        [Display(Name                            = "9003 - Character Options 1")]
        CharacterOptions1                        = 9003,
        [Display(Name                            = "9004 - Character Options 2")]
        CharacterOptions2                        = 9004,
        [Display(Name                            = "9005 - Loot Tier")]
        LootTier                                 = 9005,
        [Display(Name                            = "9006 - Generator Probability")]
        GeneratorProbability                     = 9006,
        [Display(Name                            = "9007 - Weenie Type")]
        WeenieType                               = 9007
    }

    public static class PropertyIntExtensions
    {
        public static string GetName(this IntPropertyId prop)
        {
            var description = EnumHelper.GetAttributeOfType<DisplayAttribute>(prop);
            return description?.Name ?? prop.ToString();
        }
    }
}
